server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgres://localhost:5432/customer
    username: customer
    password: customer
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
