server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: customer
    password: customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  
  sleuth:
    sampler:
      probability: 1.0 # Permet de tracer 100 % des requêtes
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
    fetch-registry: true
    register-with-eureka: true



# management:
#   tracing:
#     enabled: true
#     sampling:
#       probability: 1.0 

# micrometer:
#   tracing:
#     reporting:
#       zipkin:
#         enabled: true
#         endpoint: http://localhost:9411/api/v2/spans 
